### PR TITLE
Convert to Dist-Zilla

### PR DESCRIPTION
**Pull request by jjatria**
This makes an effort to convert this distribution to Dist::Zilla to address #33. It _should_ maintain the subtleties and the complex behaviours in the existing Makefile. I feel that moving this to a cpanfile makes things much tidier.

It includes a mailmap to try to normalise some contributor addresses, since I'm using the plugin bundle by RJBS which reads that file to list contributors.

This is part of the PRC on behalf of @cv-library

### CODE REVIEW

**Comment by karenetheridge** [comment]
I've been waiting for patches to \[@RJBS\] before I submit mine.

**Comment by jjatria** [comment]
By "yours" I assume you mean your own version of this patch?

Feel free to close this PR if that means this won't get merged.

Either way, I'm just glad this is getting done one way or the other. :slightly_smiling_face:

**Comment by rjbs** [comment]
I have merged this and will release it after some inspection of the results!  Thanks!

**Comment by jjatria** [comment]
Blast from the past! Thanks for taking a look at this

**Pull request closed without merging**
